version: '3.9'
services:

  postgres:
    container_name: postgres
    image: docker.io/bitnami/postgresql:14
    volumes:
      - ./postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
      - pg-data:/var/lib/postgresql/data
    env_file:
#      - .env.example
       - .env
    ports:
      - 5432:5432

  app:
    build: .
    container_name: app
    image: app
    env_file:
#      - .env.example
       - .env
    ports:
      - 8080:8080
    depends_on:
      - postgres

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app

volumes:
  pg-data:
